version: '3.3'
services:
  rabbitq-service:
    container_name: rabbitmg
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672 
    volumes:
      - type: bind
        source: "C:/sezo/data"
        target: /var/lib/rabbitmq
